theme: jekyll-theme-minimal
title: Diário de Bordo - UDF Computação
description: Acompanhamento das aulas de Computação
baseurl: "/udf-computacao-noturno-diario"
url: "https://lucasdoreac.github.io"

# Configurações do site
lang: pt-BR
encoding: UTF-8

# Configurações de build
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Navegação
header_pages:
  - index.md
  - disciplinas/calculo.md
  - disciplinas/sistemas.md
  - disciplinas/banco.md

# Plugins
plugins:
  - jekyll-seo-tag